config/routes.rb
Masquerade::Application.routes.draw do

  resource :account do
    get :activate
    get :password
    put :change_password
    
    resources :personas
    resources :sites
    resource :yubikey_association, :only => [:create, :destroy]
  end

  resource :password
  resource :session, :only => [:new, :create, :destroy]
  
  get "/help" => "info#help", :as => :help
  get "/safe-login" => "info#safe_login", :as => :safe_login
  
  get "/forgot_password" => "passwords#new", :as => :forgot_password
  get "/reset_password/:id" => "passwords#edit", :as => :reset_password

  get "/login" => "sessions#new", :as => :login
  get "/logout" => "sessions#destroy", :as => :logout
  post '/resend_activation_email/*account' => 'accounts#resend_activation_email', :as => :resend_activation_email

  match "/server" => "server#index", :as => :server
  match "/server/decide" => "server#decide", :as => :decide
  match "/server/proceed" => "server#proceed", :as => :proceed
  match "/server/complete" => "server#complete", :as => :complete
  match "/server/cancel" => "server#cancel", :as => :cancel
  get "/server/seatbelt/config.:format" => "server#seatbelt_config", :as => :seatbelt_config
  get "/server/seatbelt/state.:format" => "server#seatbelt_login_state", :as => :seatbelt_state

  get "/consumer" => "consumer#index", :as => :consumer
  post "/consumer/start" => "consumer#start", :as => :consumer_start
  match "/consumer/complete" => "consumer#complete", :as => :consumer_complete

  get "/*account" => "accounts#show", :as => :identity

  root :to => "info#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  belongs_to :account
  has_many :sites, :dependent => :destroy
  
  validates_presence_of :account
  validates_presence_of :title
  validates_uniqueness_of :title, :scope => :account_id
  
  before_destroy :check_deletable!
  
  attr_protected :account_id, :deletable
  
  class NotDeletable < StandardError; end
  
  def self.properties
    Persona.mappings.keys
  end

  def self.attribute_name_for_type_uri(type_uri)
    prop = mappings.detect { |i| i[1].include?(type_uri) }
    prop ? prop[0] : nil
  end
  
  # Returns the personas attribute for the given SReg name or AX Type URI
  def property(type)
    prop = Persona.mappings.detect { |i| i[1].include?(type) }
    prop ? self.send(prop[0]).to_s : nil
  end
  
  def date_of_birth
    "#{dob_year? ? dob_year : '0000'}-#{dob_month? ? dob_month.to_s.rjust(2, '0') : '00'}-#{dob_day? ? dob_day.to_s.rjust(2, '0') : '00'}"
  end
  
  def date_of_birth=(dob)
    res = dob.split("-")
    self.dob_year = res[0]
    self.dob_month = res[1]
    self.dob_day = res[2]
    dob
  end
  
  protected
  
  def check_deletable!
    raise NotDeletable unless deletable
  end
  
  private
  
  # Mappings for SReg names and AX Type URIs to attributes
  def self.mappings
    Masquerade::Application::Config['attribute_mappings']
  end
  
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
	
	before_filter :login_required
	before_filter :find_account
	before_filter :find_persona, :only => [:show, :edit, :update, :destroy]
	before_filter :store_return_url, :only => [:new, :edit]
	
	def index
		@personas = @account.personas.all

		respond_to do |format|
			format.html
		end
	end
	
	def new
		@persona = @account.personas.new

		respond_to do |format|
			format.html
		end
	end
	
	def create	
		@persona = @account.personas.new(params[:persona])

		respond_to do |format|
			begin
				@persona.save!
				flash[:notice] = t(:persona_successfully_created)
				format.html { redirect_back_or_default account_personas_path }
			rescue ActiveRecord::RecordInvalid
				format.html { render :action => "new" }
			end
		end
	end
	
	def update
		respond_to do |format|
			begin
				@persona.update_attributes(params[:persona])
				flash[:notice] = t(:persona_updated)
				format.html { redirect_back_or_default account_personas_path }
			rescue ActiveRecord::RecordInvalid, ActiveRecord::MultiparameterAssignmentErrors
				format.html { render :action => "edit" }
			end
		end
	end
	
	def destroy
		respond_to do |format|
			begin
				@persona.destroy
			rescue Persona::NotDeletable
				flash[:alert] = t(:persona_cannot_be_deleted)
			end
			format.html { redirect_to account_personas_path }
		end
	end
	
	private
	
	def find_persona
		@persona = @account.personas.find(params[:id])
	end
	
	def redirect_back_or_default(default)
		case session[:return_to]
		when decide_path then redirect_to decide_path(:persona_id => @persona.id)
	  else super(default)
    end
	end
	
  def store_return_url
    store_location(params[:return]) unless params[:return].blank?
  end
	
end

app/helpers/personas_helper.rb
module PersonasHelper

  # get list of codes and names sorted by country name
  def countries_for_select
    I18nData.countries.map{|pair| pair.reverse}.sort{|x,y| x.first <=> y.first}
  end

  # get list of codes and names sorted by language name
  def languages_for_select
    I18nData.languages.map{|pair| pair.reverse}.sort{|x,y| x.first <=> y.first}
  end

end

app/views/personas/_form.html.erb
	<div class="row inline space">
		<%= form.label :title, t(:title) %>
		<%= form.text_field :title %>
	</div>
	
	<h3><%=t :personal_information %></h3>
	<div class="row inline">
		<%= form.label :nickname, property_label_text(:nickname) %>
  	<%= form.text_field :nickname %>
	</div>
	<div class="row inline">
		<%= form.label :fullname, property_label_text(:fullname) %>
  	<%= form.text_field :fullname %>
	</div>
	<div class="row inline">
		<%= form.label :email, property_label_text(:email) %>
  	<%= form.text_field :email %>
	</div>
	<div class="row inline">
		<%= form.label :address, property_label_text(:address) %>
  	<%= form.text_field :address %>
	</div>
	<div class="row inline">
		<%= form.label :address_additional, property_label_text(:address_additional) %>
  	<%= form.text_field :address_additional %>
	</div>
	<div class="row inline">
		<%= form.label :postcode, property_label_text(:postcode) %>
  	<%= form.text_field :postcode %>
	</div>
	<div class="row inline">
		<%= form.label :city, property_label_text(:city) %>
  	<%= form.text_field :city %>
	</div>
	<div class="row inline">
		<%= form.label :state, property_label_text(:state) %>
  	<%= form.text_field :state %>
	</div>
	<div class="row inline">
		<%= form.label :country, property_label_text(:country) %>
  	<%= form.select :country, countries_for_select, { :include_blank => true } %>
	</div>
	<div class="row inline">
		<%= form.label :language, property_label_text(:language) %>
  	<%= form.select :language, languages_for_select, { :include_blank => true } %>
	</div>
	<div class="row inline">
		<%= form.label :timezone, property_label_text(:timezone) %>
  	<%= form.select :timezone, ActiveSupport::TimeZone::MAPPING.values.sort, { :include_blank => true } %>
	</div>
	<div class="row inline">
		<%= form.label :gender, property_label_text(:gender) %>
  	<%= form.select :gender, [['Male', 'M'], ['Female', 'F']], { :include_blank => true } %>
	</div>
	<div class="row inline space">
		<%= form.label :dob_day, property_label_text(:dob) %>
  	<%= select_day @persona.dob_day, :prefix => 'persona', :field_name => 'dob_day', :include_blank => true %>
		<%= select_month @persona.dob_month, :prefix => 'persona', :field_name => 'dob_month', :include_blank => true %>
		<%= select_year @persona.dob_year, :prefix => 'persona', :field_name => 'dob_year', :include_blank => true, :start_year => (Date.today.year - 100), :end_year => Date.today.year %>
	</div>

	<h3><%=t :professional_information %></h3>
	<div class="row inline">
		<%= form.label :company_name, property_label_text(:company_name) %>
  	<%= form.text_field :company_name %>
	</div>
	<div class="row inline">
		<%= form.label :job_title, property_label_text(:job_title) %>
  	<%= form.text_field :job_title %>
	</div>
	<div class="row inline">
		<%= form.label :address_business, property_label_text(:address_business) %>
  	<%= form.text_field :address_business %>
	</div>
	<div class="row inline">
		<%= form.label :address_additional_business, property_label_text(:address_additional_business) %>
  	<%= form.text_field :address_additional_business %>
	</div>
	<div class="row inline">
		<%= form.label :postcode_business, property_label_text(:postcode_business) %>
  	<%= form.text_field :postcode_business %>
	</div>
	<div class="row inline">
		<%= form.label :city_business, property_label_text(:city_business) %>
  	<%= form.text_field :city_business %>
	</div>
	<div class="row inline">
		<%= form.label :state_business, property_label_text(:state_business) %>
  	<%= form.text_field :state_business %>
	</div>
	<div class="row inline space">
		<%= form.label :country_business, property_label_text(:country_business) %>
  	<%= form.select :country_business, countries_for_select, { :include_blank => true } %>
	</div>
	
	<h3><%=t :phone %></h3>
	<div class="row inline">
		<%= form.label :phone_home, property_label_text(:phone_home) %>
  	<%= form.text_field :phone_home %>
	</div>
	<div class="row inline">
		<%= form.label :phone_mobile, property_label_text(:phone_mobile) %>
  	<%= form.text_field :phone_mobile %>
	</div>
	<div class="row inline">
		<%= form.label :phone_fax, property_label_text(:phone_fax) %>
  	<%= form.text_field :phone_fax %>
	</div>
	<div class="row inline space">
		<%= form.label :phone_work, property_label_text(:phone_work) %>
  	<%= form.text_field :phone_work %>
	</div>
	
	<h3><%=t :instant_messaging %></h3>
	<div class="row inline">
		<%= form.label :im_aim, property_label_text(:im_aim) %>
  	<%= form.text_field :im_aim %>
	</div>
	<div class="row inline">
		<%= form.label :im_icq, property_label_text(:im_icq) %>
  	<%= form.text_field :im_icq %>
	</div>
	<div class="row inline">
		<%= form.label :im_msn, property_label_text(:im_msn) %>
  	<%= form.text_field :im_msn %>
	</div>
	<div class="row inline">
		<%= form.label :im_yahoo, property_label_text(:im_yahoo) %>
  	<%= form.text_field :im_yahoo %>
	</div>
	<div class="row inline">
		<%= form.label :im_jabber, property_label_text(:im_jabber) %>
  	<%= form.text_field :im_jabber %>
	</div>
	<div class="row inline space">
		<%= form.label :im_skype, property_label_text(:im_skype) %>
  	<%= form.text_field :im_skype %>
	</div>

	<h3><%=t :other_information %></h3>
	<div class="row inline">
		<%= form.label :biography, property_label_text(:biography) %>
  	<%= form.text_field :biography %>
	</div>
	<div class="row inline">
		<%= form.label :image_default, property_label_text(:image_default) %>
  	<%= form.text_field :image_default %>
	</div>
	<div class="row inline">
		<%= form.label :web_default, property_label_text(:web_default) %>
  	<%= form.text_field :web_default %>
	</div>
	<div class="row inline">
		<%= form.label :web_blog, property_label_text(:web_blog) %>
  	<%= form.text_field :web_blog %>
	</div>

app/views/personas/edit.html.erb
<h2><%=t :edit_your_persona, :title => h(@persona.title) %></h2>
<%= error_messages_for :persona %>

<%= form_for @persona, :url => account_persona_path(@persona) do |persona| %>
	<%= render :partial => 'personas/form', :object => persona %>
	<div>
		<%= persona.submit t(:submit_update), :class => 'labelspace' %>
	</div>
<% end %>

app/views/personas/index.html.erb
<h2><%=t :my_personas_title %></h2>

<p><%=t :personas_intro %></p>

<ul>
  <% @personas.each do |persona| %>
  <li>
		<h3><%=h persona.title%></h3>
		<div class="options">
			<%= link_to t(:edit), edit_account_persona_path(persona) %>
			<%= link_to t(:delete), account_persona_path(persona), :confirm => t(:really_want_to_delete_persona, :title => h(persona.title)), :method => :delete %>
		</div>
  </li>
  <% end %>
</ul>

<%= link_to t(:create_a_new_persona), new_account_persona_path %>

app/views/personas/new.html.erb
<h2><%=t :create_a_new_persona_title %></h2>

<%= error_messages_for :persona %>

<%= form_for @persona, :url => account_personas_path do |persona| %>
	<%= render :partial => 'personas/form', :object => persona %>
	<div>
		<%= persona.submit 'create', :class => 'labelspace' %>
	</div>
<% end %>