config/routes.rb
Masquerade::Application.routes.draw do

  resource :account do
    get :activate
    get :password
    put :change_password
    
    resources :personas
    resources :sites
    resource :yubikey_association, :only => [:create, :destroy]
  end

  resource :password
  resource :session, :only => [:new, :create, :destroy]
  
  get "/help" => "info#help", :as => :help
  get "/safe-login" => "info#safe_login", :as => :safe_login
  
  get "/forgot_password" => "passwords#new", :as => :forgot_password
  get "/reset_password/:id" => "passwords#edit", :as => :reset_password

  get "/login" => "sessions#new", :as => :login
  get "/logout" => "sessions#destroy", :as => :logout
  post '/resend_activation_email/*account' => 'accounts#resend_activation_email', :as => :resend_activation_email

  match "/server" => "server#index", :as => :server
  match "/server/decide" => "server#decide", :as => :decide
  match "/server/proceed" => "server#proceed", :as => :proceed
  match "/server/complete" => "server#complete", :as => :complete
  match "/server/cancel" => "server#cancel", :as => :cancel
  get "/server/seatbelt/config.:format" => "server#seatbelt_config", :as => :seatbelt_config
  get "/server/seatbelt/state.:format" => "server#seatbelt_login_state", :as => :seatbelt_state

  get "/consumer" => "consumer#index", :as => :consumer
  post "/consumer/start" => "consumer#start", :as => :consumer_start
  match "/consumer/complete" => "consumer#complete", :as => :consumer_complete

  get "/*account" => "accounts#show", :as => :identity

  root :to => "info#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

end

app/controllers/server_controller.rb
class ServerController < ApplicationController
  
  # CSRF-protection must be skipped, because incoming
  # OpenID requests lack an authenticity token
  skip_before_filter :verify_authenticity_token
  # Error handling
  rescue_from OpenID::Server::ProtocolError, :with => :render_openid_error
  # Actions other than index require a logged in user
  before_filter :login_required, :except => [:index, :cancel, :seatbelt_config, :seatbelt_login_state]
  before_filter :ensure_valid_checkid_request, :except => [:index, :cancel, :seatbelt_config, :seatbelt_login_state]
  after_filter :clear_checkid_request, :only => [:cancel, :complete]
  # These methods are used to display information about the request to the user
  helper_method :sreg_request, :ax_fetch_request, :ax_store_request
  
  # This is the server endpoint which handles all incoming OpenID requests.
  # Associate and CheckAuth requests are answered directly - functionality
  # therefor is provided by the ruby-openid gem. Handling of CheckId requests
  # dependents on the users login state (see handle_checkid_request).
  # Yadis requests return information about this endpoint.
  def index
    clear_checkid_request
    respond_to do |format|
      format.html do
        if openid_request.is_a?(OpenID::Server::CheckIDRequest)
          handle_checkid_request
        elsif openid_request
          handle_non_checkid_request
        else
          render :text => t(:this_is_openid_not_a_human_ressource)
        end
      end
      format.xrds
    end
  end
  
  # This action decides how to process the current request and serves as
  # dispatcher and re-entry in case the request could not be processed 
  # directly (for instance if the user had to log in first).
  # When the user has already trusted the relying party, the request will
  # be answered based on the users release policy. If the request is immediate
  # (relying party wants no user interaction, used e.g. for ajax requests)
  # the request can only be answered if no further information (like simple 
  # registration data) is requested. Otherwise the user will be redirected
  # to the decision page.
  def proceed
    identity = identifier(current_account)
    if @site = current_account.sites.find_by_url(checkid_request.trust_root)
      resp = checkid_request.answer(true, nil, identity)
      resp = add_sreg(resp, @site.sreg_properties) if sreg_request
      resp = add_ax(resp, @site.ax_properties) if ax_fetch_request
      resp = add_pape(resp, auth_policies, auth_level, auth_time)
      render_response(resp)
    elsif checkid_request.immediate && (sreg_request || ax_store_request || ax_fetch_request)
      render_response(checkid_request.answer(false))
    elsif checkid_request.immediate
      render_response(checkid_request.answer(true, nil, identity))
    else
      redirect_to decide_path
    end
  end
  
  # Displays the decision page on that the user can confirm the request and
  # choose which data should be transfered to the relying party.
  def decide
    @site = current_account.sites.find_or_initialize_by_url(checkid_request.trust_root)
    @site.persona = current_account.personas.find(params[:persona_id] || :first) if sreg_request || ax_store_request || ax_fetch_request
  end
  
  # This action is called by submitting the decision form, the information entered by
  # the user is used to answer the request. If the user decides to always trust the
  # relying party, a new site according to the release policies the will be created.
  def complete
    if params[:cancel]
      cancel
    else  
      resp = checkid_request.answer(true, nil, identifier(current_account))
      if params[:always]
        @site = current_account.sites.find_or_create_by_persona_id_and_url(params[:site][:persona_id], params[:site][:url])
        @site.update_attributes(params[:site])
      elsif sreg_request || ax_fetch_request
        @site = current_account.sites.find_or_initialize_by_persona_id_and_url(params[:site][:persona_id], params[:site][:url])
        @site.attributes = params[:site]
      elsif ax_store_request
        @site = current_account.sites.find_or_initialize_by_persona_id_and_url(params[:site][:persona_id], params[:site][:url])
        not_supported, not_accepted, accepted = [], [], []
        ax_store_request.data.each do |type_uri, values|
          if property = Persona.attribute_name_for_type_uri(type_uri)
            store_attribute = params[:site][:ax_store][property.to_sym]
            if store_attribute && !store_attribute[:value].blank?
              @site.persona.update_attribute(property, values.first)
              accepted << type_uri
            else
              not_accepted << type_uri
            end
          else
            not_supported << type_uri
          end
        end
        ax_store_response = (accepted.count > 0) ? OpenID::AX::StoreResponse.new : OpenID::AX::StoreResponse.new(false, "None of the attributes were accepted.")
        resp.add_extension(ax_store_response)
      end
      resp = add_pape(resp, auth_policies, auth_level, auth_time)
      resp = add_sreg(resp, @site.sreg_properties) if sreg_request && @site.sreg_properties
      resp = add_ax(resp, @site.ax_properties) if ax_fetch_request && @site.ax_properties
      render_response(resp)
    end
  end
  
  # Cancels the current OpenID request
  def cancel
    redirect_to checkid_request.cancel_url
  end
  
  protected
  
  # Decides how to process an incoming checkid request. If the user is
  # already logged in he will be forwarded to the proceed action. If
  # the user is not logged in and the request is immediate, the request
  # cannot be answered successfully. In case the user is not logged in,
  # the request will be stored and the user is asked to log in.
  def handle_checkid_request
    if allow_verification?
      save_checkid_request
      redirect_to proceed_path
    elsif openid_request.immediate
      render_response(openid_request.answer(false))
    else
      reset_session
      request = save_checkid_request
      session[:return_to] = proceed_path
      redirect_to( request.from_trusted_domain? ? login_path : safe_login_path )
    end
  end
  
  # Stores the current OpenID request.
  # Returns the OpenIdRequest
  def save_checkid_request
    clear_checkid_request
    request = OpenIdRequest.create(:parameters => openid_params)
    session[:request_token] = request.token

    request
  end
  
  # Deletes the old request when a new one comes in.
  def clear_checkid_request
    unless session[:request_token].blank?
      OpenIdRequest.destroy_all :token => session[:request_token]
      session[:request_token] = nil
    end
  end
  
  # Use this as before_filter for every CheckID request based action.
  # Loads the current openid request and cancels if none can be found.
  # The user has to log in, if he has not verified his ownership of
  # the identifier, yet.
  def ensure_valid_checkid_request
    self.openid_request = checkid_request
    if !openid_request.is_a?(OpenID::Server::CheckIDRequest)
      redirect_to root_path, :alert => t(:identity_verification_request_invalid)
    elsif !allow_verification?
      flash[:notice] = logged_in? && !pape_requirements_met?(auth_time) ?
        t(:service_provider_requires_reauthentication_last_login_too_long_ago) :
        t(:login_to_verify_identity)
      session[:return_to] = proceed_path
      redirect_to login_path
    end
  end
  
  # The user must be logged in, he must be the owner of the claimed identifier
  # and the PAPE requirements must be met if applicable.
  def allow_verification?
    logged_in? && correct_identifier? && pape_requirements_met?(auth_time)
  end
  
  # Is the user allowed to verify the claimed identifier? The user
  # must be logged in, so that we know his identifier or the identifier
  # has to be selected by the server (id_select).
  def correct_identifier?
    (openid_request.identity == identifier(current_account) || openid_request.id_select)
  end
  
  # Clears the stored request and answers
  def render_response(resp)
    clear_checkid_request
    render_openid_response(resp)
  end
  
  # Transforms the parameters from the form to valid AX response values
  def transform_ax_data(parameters)
    data = {}
    parameters.each_pair do |key, details|
      if details['value']
        data["type.#{key}"] = details['type']
        data["value.#{key}"] = details['value']
      end
    end
    data
  end
  
  # Renders the exception message as text output
  def render_openid_error(exception)
    error = case exception
    when OpenID::Server::MalformedTrustRoot then "Malformed trust root '#{exception.to_s}'"
    else exception.to_s
    end
    render :text => "Invalid OpenID request: #{error}", :status => 500
  end
  
  private
  
  # The NIST Assurance Level, see:
  # http://openid.net/specs/openid-provider-authentication-policy-extension-1_0-01.html#anchor12
  def auth_level
    if Masquerade::Application::Config['use_ssl']
      current_account.last_authenticated_with_yubikey? ? 3 : 2
    else
      0
    end
  end
  
  def auth_time
    current_account.last_authenticated_at
  end
  
  def auth_policies
    current_account.last_authenticated_with_yubikey? ? 
      [OpenID::PAPE::AUTH_MULTI_FACTOR, OpenID::PAPE::AUTH_PHISHING_RESISTANT] :
      []
  end
  
end

app/helpers/server_helper.rb
module ServerHelper
  
  def sreg_request_for_field(field_name)
    if sreg_request.required.include?(field_name)
      t(:required)
    elsif sreg_request.optional.include?(field_name)
      t(:optional)
    end
  end
  
  def ax_request_for_field(ax_attribute)
    ax_attribute.required ? t(:required) : t(:optional)
  end
  
end

app/views/server/decide.html.erb
<h2><%= t(:identity_request_from_host, :host => h(extract_host(@site.url))).html_safe %></h2>

<% if ax_store_request %>
<p><%= t(:trust_root_sends_some_personal_data, :trust_root => "<strong>#{h checkid_request.trust_root}</strong>").html_safe %><br />
<% if @site.persona %>
<%= t(:select_information_to_accept) %></p>
<p class="note"><%= t(:attributes_will_be_added_to_persona, :persona => "<strong>#{h @site.persona.title}</strong>",
  :choose_link => link_to_function(t(:choose_other_persona), 'Element.toggle("persona_select")')).html_safe %></p>
<% else %>
<p><%= t(:identity_request_missing_persona, :create_link => link_to(t(:create_persona_link), new_account_persona_path(:return => decide_path))).html_safe %></p>
<% end %>

<% elsif sreg_request || ax_fetch_request %>
<p><%= t(:trust_root_requests_some_personal_data, :trust_root => "<strong>#{h checkid_request.trust_root}</strong>").html_safe %><br />
<% if @site.persona %>
<%= t(:select_information_to_submit) %></p>
<p class="note"><%= t(:attributes_are_shown_from_persona, :persona => "<strong>#{h @site.persona.title}</strong>").html_safe %><br />
<%= t(:to_submit_other_values_you_can_edit_or_choose, 
  :edit_link => link_to(t(:edit_persona_link), edit_account_persona_path(@site.persona, :return => decide_path(:persona_id => @site.persona.id))),
  :choose_link => link_to_function(t(:choose_other_persona), 'Element.toggle("persona_select")')).html_safe %></p>
<% else %>
<p><%= t(:identity_request_missing_persona, :create_link => link_to(t(:create_persona_link), new_account_persona_path(:return => decide_path))).html_safe %></p>
<% end %>
<% else %>
<p><%= t(:trust_root_requires_authentication, :trust_root => "<strong>#{h checkid_request.trust_root}</strong>").html_safe %></p>
<% end %>

<%= form_tag decide_path, :method => :get, :id => 'persona_select', :style => 'display:none;' do %>

	<h3><%= t(:choose_persona_title) %></h3>
	<% unless current_account.personas.empty? %>
	<div class="row">
		<select id="persona_id" name="persona_id">
			<%= options_from_collection_for_select(current_account.personas, :id, :title, @site.persona.id) %>
		</select>
	</div>
	<div>
		<%= submit_tag t(:choose_persona_submit) %> or
		<%= link_to t(:create_new_persona_link), new_account_persona_path(:return => decide_path) %>
	</div>
	<% end %>
	
<% end if sreg_request || ax_fetch_request || ax_store_request %>

<%= form_for @site, :url => complete_path do |f| %>

	<% if sreg_request || ax_fetch_request %>
	<table cellspacing="0">
    <tr>
			<th colspan="2"><h4><%= t(:requested_information_title) %></h4></th>
			<th class="disclosure"><%= t(:disclosure) %></th>
		</tr>
		<% (sreg_request.required + sreg_request.optional).each do |property| %>
		<tr>
			<td><%= label_tag "site_sreg_#{property}", property_label_text(property) %></td>
			<td><%= label_tag "site_sreg_#{property}", @site.persona.property(property) %></td>
			<td>
				<%= check_box_tag "site[sreg][#{property}]", @site.persona.property(property), sreg_request.required.include?(property), :id => "site_sreg_#{property}", :class => sreg_request_for_field(property) %>
				<%= label_tag "site_sreg_#{property}", sreg_request_for_field(property), :class => 'note' %>
			</td>
		</tr>
		<% end if sreg_request %>
		<% ax_fetch_request.attributes.each do |property| %>
		<% supported = !Persona.attribute_name_for_type_uri(property.type_uri).nil? %>
		<tr>
			<td><%= label_tag "site_ax_fetch_#{property.ns_alias}", property_label_text(property.ns_alias) %></td>
			<td><%= label_tag "site_ax_fetch_#{property.ns_alias}", supported ? @site.persona.property(property.type_uri) : t(:not_supported), :class => supported ? nil : 'note' %></td>
			<td>
				<%= check_box_tag "site[ax_fetch][#{property.ns_alias}][value]", @site.persona.property(property.type_uri), property.required, :id => "site_ax_fetch_#{property.ns_alias}", :class => ax_request_for_field(property), :disabled => !supported %>
				<%= hidden_field_tag "site[ax_fetch][#{property.ns_alias}][type]", property.type_uri, :id => "site_ax_fetch_type_#{property.ns_alias}" %>
				<%= label_tag "site_ax_fetch_#{property.ns_alias}", ax_request_for_field(property), :class => 'note' %>
			</td>
		</tr>
		<% end if ax_fetch_request %>
	</table>
	<% end %>
	
	<% if ax_store_request %>
	<table cellspacing="0">
    <tr>
			<th colspan="2"><h4><%= t(:sent_information_title) %></h4></th>
			<th class="current"><%= t(:current) %></th>
			<th class="accept"><%= t(:accept) %></th>
		</tr>
		<% ax_store_request.data.each do |type_uri, value| %>
		<% if attribute = Persona.attribute_name_for_type_uri(type_uri) %>
		<tr>
			<td><%= label_tag "site_ax_store_#{attribute}", property_label_text_for_type_uri(type_uri) %></td>
			<td><%= label_tag "site_ax_store_#{attribute}", value %></td>
			<td><%= label_tag "site_ax_store_#{attribute}", @site.persona.property(type_uri) %></td>
			<td>
				<%= check_box_tag "site[ax_store][#{attribute}][value]", value, false, :id => "site_ax_store_#{attribute}" %>
				<%= hidden_field_tag "site[ax_store][#{attribute}][type]", type_uri, :id => "site_ax_store_type_#{attribute}" %>
			</td>
		</tr>
  	<% end %>
		<% end %>
	</table>
	<% end %>
	
	<div>
		<% if sreg_request || ax_fetch_request || ax_store_request %>
		<%= f.hidden_field :persona_id %>
		<%= f.hidden_field :url %>
		<% end %>
		
		<% if sreg_request || ax_fetch_request %>
		<%= submit_tag t(:trust_site_only_this_time), :name => 'temporary', :class => 'space' %>
		<%= submit_tag t(:always_trust_site), :name => 'always', :class => 'space' %>
		<% else %>
		<%= submit_tag t(:approve_request), :name => 'temporary', :class => 'space' %>
		<% end %>
		<%= submit_tag t(:cancel_request), :name => 'cancel' %>
	</div>
	
<% end unless current_account.personas.empty? %>