config/routes.rb
Masquerade::Application.routes.draw do

  resource :account do
    get :activate
    get :password
    put :change_password
    
    resources :personas
    resources :sites
    resource :yubikey_association, :only => [:create, :destroy]
  end

  resource :password
  resource :session, :only => [:new, :create, :destroy]
  
  get "/help" => "info#help", :as => :help
  get "/safe-login" => "info#safe_login", :as => :safe_login
  
  get "/forgot_password" => "passwords#new", :as => :forgot_password
  get "/reset_password/:id" => "passwords#edit", :as => :reset_password

  get "/login" => "sessions#new", :as => :login
  get "/logout" => "sessions#destroy", :as => :logout
  post '/resend_activation_email/*account' => 'accounts#resend_activation_email', :as => :resend_activation_email

  match "/server" => "server#index", :as => :server
  match "/server/decide" => "server#decide", :as => :decide
  match "/server/proceed" => "server#proceed", :as => :proceed
  match "/server/complete" => "server#complete", :as => :complete
  match "/server/cancel" => "server#cancel", :as => :cancel
  get "/server/seatbelt/config.:format" => "server#seatbelt_config", :as => :seatbelt_config
  get "/server/seatbelt/state.:format" => "server#seatbelt_login_state", :as => :seatbelt_state

  get "/consumer" => "consumer#index", :as => :consumer
  post "/consumer/start" => "consumer#start", :as => :consumer_start
  match "/consumer/complete" => "consumer#complete", :as => :consumer_complete

  get "/*account" => "accounts#show", :as => :identity

  root :to => "info#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title><%=h page_title %></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<% if identity_page? %>
		<meta http-equiv="X-XRDS-Location" content="<%= identity_url(:account => @account, :format => :xrds, :protocol => scheme) %>" />
		<link rel="openid.server openid2.provider" href="<%= endpoint_url %>" />
		<% elsif home_page? %>
		<meta http-equiv="X-XRDS-Location" content="<%= server_url(:format => :xrds, :protocol => scheme) %>" />
		<% end %>
		<%= csrf_meta_tag %>
		<link rel="seatbelt.config" type="application/xml" href="<%= seatbelt_config_url(:format => :xml, :protocol => scheme) %>" />
		<link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" />
		<link rel="icon" href="/favicon.ico" type="image/ico" />
		<%= stylesheet_link_tag 'application' %>
		<%= javascript_include_tag 'prototype' %>
		<%= javascript_include_tag :defaults %>
	</head>
	<body>
		<div id="head">
      <div class="wrap">
				<h1><%= link_to Masquerade::Application::Config['name'], root_path %></h1>
				<ul id="navi">
				<% if logged_in? %>
					<% unless checkid_request %>
					<%= nav t(:my_identity), identity_path(current_account), 'accounts' => ['show'] %>
					<%= nav t(:my_profile), edit_account_path, 'accounts' => ['edit', 'update'] %>
					<%= nav t(:my_personas), account_personas_path, 'personas' => [] %>
					<%= nav t(:my_trusted_sites), account_sites_path, 'sites' => [] %>
					<% if not auth_type_used == :basic %>
						<%= nav t(:logout), logout_path %>
					<% end %>
					<% else %>
					<%= nav t(:current_verification_request), proceed_path, 'server' => [] %>
					<% end %>
				<% else %>
					<%= nav t(:login_link), login_path, 'sessions' => ['new', 'create'] %>
					<% unless Masquerade::Application::Config['disable_registration'] %>
						<%= nav t(:signup_link), new_account_path, 'accounts' => ['new', 'create'] %>
					<% end %>
					<%= nav t(:help), help_path, 'info' => ['help'] %>
				<% end %>
				</ul>
			</div>
		</div>
		<div id="main">
			<div class="wrap">
    		<% if flash[:notice] %><div class="notice"><%=simple_format h(flash[:notice]) %></div><% end %>
    		<% if flash[:alert] %>
			<div class="error">
				<%=simple_format h(flash[:alert]) %>

				<% unless params[:resend_activation_for].blank? -%>
					<%= button_to t(:resend_activation_email), resend_activation_email_path(:account => params[:resend_activation_for]) -%>
				<%- end %>
			</div>
		<% end %>
				<%= yield %>
			</div>
		</div>
		<div id="foot">
			<div class="wrap">
				<span class="note">
					powered by <%= link_to 'masquerade', 'https://github.com/dennisreimann/masquerade/' %>
					and <%= link_to image_tag('openid_symbol.png') + " OpenID", 'http://openid.net/' %> |
					<%= link_to t(:get_help), help_path %>
				</span>
			</div>
		</div>
	</body>
</html>

app/views/layouts/consumer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title><%=t :openid_consumer_testsuite_title %></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<%= stylesheet_link_tag 'application' %>
		<link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" />
		<link rel="icon" href="/favicon.ico" type="image/ico" />
	</head>
	<body>
		<div id="head">
    		<h1><%=t :relying_party_title %></h1>
		</div>
		<div id="main">
			<div class="wrap">
  			<h2><%=t :openid_consumer_testsuite_title %></h2>
	    	<% if flash[:notice] %><div class="notice"><%=simple_format h flash[:notice] %></div><% end %>
	    	<% if flash[:alert] %><div class="error"><%=simple_format h flash[:alert] %></div><% end %>
				<%= yield %>
			</div>
		</div>
		<div id="foot">
			<div class="wrap">
				<span class="note">
					powered by <%= link_to "masquerade", 'http://dennisbloete.de/projects/masquerade/' %>
					and <%= link_to image_tag('openid_symbol.png') + " OpenID", 'http://openid.net/' %>
				</span>
			</div>
		</div>
	</body>
</html>