config/routes.rb
Masquerade::Application.routes.draw do

  resource :account do
    get :activate
    get :password
    put :change_password
    
    resources :personas
    resources :sites
    resource :yubikey_association, :only => [:create, :destroy]
  end

  resource :password
  resource :session, :only => [:new, :create, :destroy]
  
  get "/help" => "info#help", :as => :help
  get "/safe-login" => "info#safe_login", :as => :safe_login
  
  get "/forgot_password" => "passwords#new", :as => :forgot_password
  get "/reset_password/:id" => "passwords#edit", :as => :reset_password

  get "/login" => "sessions#new", :as => :login
  get "/logout" => "sessions#destroy", :as => :logout
  post '/resend_activation_email/*account' => 'accounts#resend_activation_email', :as => :resend_activation_email

  match "/server" => "server#index", :as => :server
  match "/server/decide" => "server#decide", :as => :decide
  match "/server/proceed" => "server#proceed", :as => :proceed
  match "/server/complete" => "server#complete", :as => :complete
  match "/server/cancel" => "server#cancel", :as => :cancel
  get "/server/seatbelt/config.:format" => "server#seatbelt_config", :as => :seatbelt_config
  get "/server/seatbelt/state.:format" => "server#seatbelt_login_state", :as => :seatbelt_state

  get "/consumer" => "consumer#index", :as => :consumer
  post "/consumer/start" => "consumer#start", :as => :consumer_start
  match "/consumer/complete" => "consumer#complete", :as => :consumer_complete

  get "/*account" => "accounts#show", :as => :identity

  root :to => "info#index"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  has_many :personas, :dependent => :delete_all, :order => 'id ASC'
  has_many :sites, :dependent => :destroy
  belongs_to :public_persona, :class_name => "Persona"

  validates_presence_of :login
  validates_length_of :login, :within => 3..254
  validates_uniqueness_of :login, :case_sensitive => false
  validates_format_of :login, :with => /^[A-Za-z0-9_@.-]+$/
  validates_presence_of :email
  validates_uniqueness_of :email, :case_sensitive => false
  validates_format_of :email, :with => /(^([^@\s]+)@((?:[-_a-z0-9]+\.)+[a-z]{2,})$)|(^$)/i
  validates_presence_of :password, :if => :password_required?
  validates_presence_of :password_confirmation, :if => :password_required?
  validates_length_of :password, :within => 6..40, :if => :password_required?
  validates_confirmation_of :password, :if => :password_required?
  # check `rake routes' for whether this list is still complete when routes are changed
  validates_exclusion_of :login, :in => %w[account session password help safe-login forgot_password reset_password login logout server consumer]
  
  before_save   :encrypt_password
  before_create :make_activation_code
  
  attr_accessible :login, :email, :password, :password_confirmation, :public_persona_id, :yubikey_mandatory
  attr_accessor :password
  
  class ActivationCodeNotFound < StandardError; end
  class AlreadyActivated < StandardError
    attr_reader :user, :message
    def initialize(account, message=nil)
      @message, @account = message, account
    end
  end
  
  # Finds the user with the corresponding activation code, activates their account and returns the user.
  #
  # Raises:
  # [Account::ActivationCodeNotFound] if there is no user with the corresponding activation code
  # [Account::AlreadyActivated] if the user with the corresponding activation code has already activated their account
  def self.find_and_activate!(activation_code)
    raise ArgumentError if activation_code.nil?
    user = find_by_activation_code(activation_code)
    raise ActivationCodeNotFound unless user
    raise AlreadyActivated.new(user) if user.active?
    user.send(:activate!)
    user
  end
  
  def to_param
    login
  end
  
  # The existence of an activation code means they have not activated yet
  def active?
    activation_code.nil?
  end

  # True if the user has just been activated
  def pending?
    @activated
  end
  
  # Does the user have the possibility to authenticate with a one time password?
  def has_otp_device?
    !yubico_identity.nil?
  end
  
  # Authenticates a user by their login name and password.
  # Returns the user or nil.
  def self.authenticate(login, password, basic_auth_used=false)
    a = Account.find_by_login(login)
    if a.nil? and Masquerade::Application::Config['create_auth_ondemand']['enabled']
      # Need to set some password - but is never used
      if Masquerade::Application::Config['create_auth_ondemand']['random_password']
        pw = SecureRandom.hex(13)
      else
        pw = password
      end
      a = Account.create!(:login => login, :password => pw, :password_confirmation => pw, :email => "#{login}@#{Masquerade::Application::Config['create_auth_ondemand']['default_mail_domain']}")
    end

    if not a.nil? and a.active? and a.enabled
      if a.authenticated?(password) or (Masquerade::Application::Config['trust_basic_auth'] and basic_auth_used)
        a.last_authenticated_at, a.last_authenticated_with_yubikey = Time.now, a.authenticated_with_yubikey?
        a.save(:validate => false)
        return a
      end
    end
  end

  # Encrypts some data with the salt.
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  # Encrypts the password with the user salt
  def encrypt(password)
    self.class.encrypt(password, salt)
  end
  
  def authenticated?(password)
    if password.nil?
      return false
    elsif password.length < 50 && !(yubico_identity? && yubikey_mandatory?)
      encrypt(password) == crypted_password
    elsif Masquerade::Application::Config['can_use_yubikey']
      password, yubico_otp = Account.split_password_and_yubico_otp(password)
      encrypt(password) == crypted_password && @authenticated_with_yubikey = yubikey_authenticated?(yubico_otp)
    end
  end
  
  # Is the Yubico OTP valid and belongs to this account?
  def yubikey_authenticated?(otp)
    if yubico_identity? && Account.verify_yubico_otp(otp)
      (Account.extract_yubico_identity_from_otp(otp) == yubico_identity)
    else
      false
    end
  end
  
  def authenticated_with_yubikey?
    @authenticated_with_yubikey || false
  end
  
  def associate_with_yubikey(otp)
    if Account.verify_yubico_otp(otp)
      self.yubico_identity = Account.extract_yubico_identity_from_otp(otp)
      save(:validate => false)
    else
      false
    end
  end
  
  def remember_token?
    remember_token_expires_at && Time.now.utc < remember_token_expires_at 
  end

  # These create and unset the fields required for remembering users between browser closes
  def remember_me
    remember_me_for 2.weeks
  end

  def remember_me_for(time)
    remember_me_until time.from_now.utc
  end

  def remember_me_until(time)
    self.remember_token_expires_at = time
    self.remember_token = encrypt("#{email}--#{remember_token_expires_at}")
    save(:validate => false)
  end

  def forget_me
    self.remember_token_expires_at = nil
    self.remember_token = nil
    save(:validate => false)
  end

  def forgot_password!
    @forgotten_password = true
    self.make_password_reset_code
    self.save
  end
  
  # First update the password_reset_code before setting the
  # reset_password flag to avoid duplicate email notifications.
  def reset_password
    update_attribute(:password_reset_code, nil)
    @reset_password = true
  end  
  
  def recently_forgot_password?
    @forgotten_password
  end

  def recently_reset_password?
    @reset_password
  end
  
  def disable!
    update_attribute(:enabled, false)
  end
  
  protected
  
  def encrypt_password
    return if password.blank?
    self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{login}--") if new_record?
    self.crypted_password = encrypt(password)
  end
    
  def password_required?
    crypted_password.blank? || !password.blank?
  end
  
  def make_activation_code
    if Masquerade::Application::Config['send_activation_mail']
      self.activation_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
    end
  end
  
  def make_password_reset_code
    self.password_reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
  end
  
  private
  
  def activate!
    @activated = true
    self.activated_at = Time.now.utc
    self.activation_code = nil
    self.save
  end
  
  # Returns the first twelve chars from the Yubico OTP,
  # which are used to identify a Yubikey
  def self.extract_yubico_identity_from_otp(yubico_otp)
    yubico_otp[0..11]
  end
  
  # Recieves a login token which consists of the users password and
  # a Yubico one time password (the otp is always 44 characters long)
  def self.split_password_and_yubico_otp(token)
    token.reverse!
    yubico_otp = token.slice!(0..43).reverse
    password = token.reverse
    [password, yubico_otp]
  end
  
  # Utilizes the Yubico library to verify an one time password 
  def self.verify_yubico_otp(otp)
    yubico = Yubico.new(Masquerade::Application::Config['yubico']['id'], Masquerade::Application::Config['yubico']['api_key'])
    yubico.verify(otp) == Yubico::E_OK
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_filter :login_required, :except => [:show, :new, :create, :activate, :resend_activation_email]
  before_filter :detect_xrds, :only => :show
  
  def show
    @account = Account.first(:conditions => ['login = ? AND enabled = ?', params[:account], true])
    raise ActiveRecord::RecordNotFound if @account.nil?
    
    respond_to do |format|
      format.html do
        response.headers['X-XRDS-Location'] = identity_url(:account => @account, :format => :xrds, :protocol => scheme)
      end
      format.xrds
    end
  end
  
  def new
    if Masquerade::Application::Config['disable_registration']
      return render_404
    end
    @account = Account.new
  end

  def create
    if Masquerade::Application::Config['disable_registration']
      return render_404
    end

    cookies.delete :auth_token
    attrs = params[:account]

    if email_as_login?
      attrs[:login] = attrs[:email]
    end
    
    @account = Account.new(attrs)
    begin
      @account.save!
      if Masquerade::Application::Config['send_activation_mail']
        redirect_to login_path, :notice => t(:thanks_for_signing_up_activation_link)
      else
        redirect_to login_path, :notice => t(:thanks_for_signing_up)
      end
    rescue ActiveRecord::RecordInvalid
      render :action => 'new'
    end
  end

  def edit
    @account = current_account
  end

  def update
    @account = current_account
    attrs = params[:account]
    attrs.delete(:email) if email_as_login?
    attrs.delete(:login)
    
    if @account.update_attributes(attrs)
      redirect_to edit_account_path(:account => current_account), :notice => t(:profile_updated)
    else
      render :action => 'edit'
    end
  end

  def destroy
    unless Masquerade::Application::Config['can_disable_account']
      return render_404
    end

    @account = current_account
    if @account.authenticated?(params[:confirmation_password])
      @account.disable!
      current_account.forget_me 
      cookies.delete :auth_token
      reset_session
      redirect_to root_path, :notice => t(:account_disabled)
    else
      redirect_to edit_account_path, :alert => t(:entered_password_is_wrong)
    end
  end
  
  def activate
    unless Masquerade::Application::Config['send_activation_mail']
      return render_404
    end

    begin
      account = Account.find_and_activate!(params[:id])
      redirect_to login_path, :notice => t(:account_activated_login_now)
    rescue ArgumentError, Account::ActivationCodeNotFound
      redirect_to new_account_path, :alert => t(:couldnt_find_account_with_code_create_new_one)
    rescue Account::AlreadyActivated
      redirect_to login_path, :alert => t(:account_already_activated_please_login)
    end
  end
  
  def change_password
    unless Masquerade::Application::Config['can_change_password']
      return render_404
    end

    if Account.authenticate(current_account.login, params[:old_password])
      if ((params[:password] == params[:password_confirmation]) && !params[:password_confirmation].blank?)
        current_account.password_confirmation = params[:password_confirmation]
        current_account.password = params[:password]        
        if current_account.save
          redirect_to edit_account_path(:account => current_account), :notice => t(:password_has_been_changed)
        else
          redirect_to edit_account_path, :alert => t(:sorry_password_couldnt_be_changed)
        end
      else
        @old_password = params[:old_password]
        redirect_to edit_account_path, :alert => t(:confirmation_of_new_password_invalid)
      end
    else
      redirect_to edit_account_path, :alert => t(:old_password_incorrect)
    end 
  end

  def resend_activation_email
    account = Account.find_by_login(params[:account])
    
    if account && !account.active?
      AccountMailer.signup_notification(account).deliver 
      flash[:notice] = t(:activation_link_resent)
    else
      flash[:alert] = t(:account_already_activated_or_missing)
    end
    
    redirect_to login_path
  end

  protected

  def detect_xrds
    if params[:account] =~ /\A(.+)\.xrds\z/
      request.format = :xrds
      params[:account] = $1
    end
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_hcard.html.erb
<div id="hcard-<%= persona.fullname.gsub(/\s/, '-') if persona.fullname %>" class="vcard">
	<% if persona.web_blog and !persona.web_blog.empty? %>
 <a class="url fn" href='<%= persona.web_blog %>' ><%= persona.fullname %></a>
    <% else %>
 <span class="fn"><%= persona.fullname %></span>
    <% end %>
 <% if persona.company_name%>
 <div class="org"><%= persona.company_name %></div>
 <% end %>
 <% if persona.email %>
 <a class="email" href="mailto:<%= persona.email %>"><%= persona.email %></a>
 <% end %>
 <% if persona.address %>
 <div class="adr">
  <div class="street-address"><%= persona.address %></div>
  <span class="locality"><%= persona.city %></span>
, 
  <span class="region"><%= persona.state %></span>
, 
  <span class="postal-code"><%= persona.postcode %></span>

  <span class="country-name"><%= persona.country %></span>

 </div>
 <% end %>
 <% if persona.phone_mobile%>
 <div class="tel"><%= persona.phone_mobile%></div>
 <% end %>
</div>

app/views/accounts/edit.html.erb
<h2><%=t :my_profile %></h2>

<%= error_messages_for :account %>
 
<%= form_for :account, :url => account_path, :html => { :method => :put } do |f| %>
	<% unless email_as_login? -%>
	<div class="row">
		<%= f.label :email, t(:email) %>
		<%= f.text_field :email %>
	</div>
	<% end -%>
	
	<div class="row">
		<%= f.label :public_persona_id, t(:public_persona) %>
  	<%= f.select :public_persona_id, @account.personas.map{ |p| [ p.title, p.id ]}, :include_blank => true %>
	</div>
	
	<div>
	  <%= f.submit t(:submit_update) %>
  </div>
<% end %>

<% if Masquerade::Application::Config['can_change_password'] %>
  <h2><%=t :my_password %></h2>
  <%= form_tag change_password_account_path, :method => :put do %>
    <div class="row">
      <%= label_tag :old_password, t(:old_password) %>
      <%= password_field_tag :old_password %>
    </div>
    <div class="row">
      <%= label_tag :password, t(:new_password_minimum_6_characters).html_safe %>
      <%= password_field_tag :password %>
    </div>
    <div class="row">
      <%= label_tag :password_confirmation, t(:password_confirmation) %>
      <%= password_field_tag :password_confirmation %>
    </div>
    <div>
      <%= submit_tag t(:submit_update) %>
    </div>
  <% end %>
<% end %>

<% if Masquerade::Application::Config['can_use_yubikey'] %>
  <h2><%=t :my_yubikey %></h2>
  <% if @account.yubico_identity? %>
  <%= form_tag account_yubikey_association_path, :method => :delete do %>
    <div class="row">
      <p><%=t :your_account_is_associated_with_the_yubico_identity %> <strong><%= @account.yubico_identity %></strong></p>
      <p class="note"><%=t :yubikey_how_to_use %></p>
    </div>
    <div>
      <%= submit_tag t(:remove_association) %>
    </div>
  <% end %>

  <%= form_for :account, :url => account_path, :html => { :method => :put } do |f| %>
    <div>
      <p>
        <% if @account.yubikey_mandatory? %>
         <%=t :your_yubikey_is_mandatory_for_login %>
        <% else %>
         <%=t :your_yubikey_is_optional_for_login %>
        <% end %>
      </p>
      <div>
        <%= f.hidden_field :yubikey_mandatory, :value => (@account.yubikey_mandatory ? 0 : 1)  %>
        <%= submit_tag( @account.yubikey_mandatory ? t(:make_my_yubikey_optional) : t(:make_my_yubikey_mandatory) ) %>
      </div>
    </div>
  <% end %>

  <% else %>
  <%= form_tag account_yubikey_association_path do %>
    <div class="row">
      <%= label_tag :yubico_otp, t(:your_yubikey_a_one_time_password).html_safe %>
      <%= password_field_tag :yubico_otp %>
    </div>
    <div>
      <%= submit_tag t(:associate_account_with_yubikey) %>
    </div>
  <% end %>
  <% end %>
<% end %>

<% if Masquerade::Application::Config['can_disable_account'] %>
  <h2><%=t :disable_my_account %></h2>

  <%= form_tag account_path, :method => :delete do %>
    <p><%=t :wont_be_possible_to_reclaim_identifier %> <%= identifier(current_account) %></p>
    <div class="row">
      <%= label_tag :confirmation_password, t(:confirm_by_entering_password) %>
        <%= password_field_tag :confirmation_password, '' %>
    </div>
    <div>
      <%= submit_tag t(:delete_my_account_and_data) %>
    </div>
  <% end %>
<% end %>

app/views/accounts/new.html.erb
<h2><%=t :signup_title %></h2>

<%= error_messages_for :account %>

<%= form_for :account, :url => account_path do |f| -%>
	<% unless email_as_login? -%>
	<div class="row">
		<%= f.label :login, t(:login) %>
		<%= f.text_field :login %>
	</div>
	<% end -%>
	<div class="row">
		<%= f.label :email, t(:email) %>
		<%= f.text_field :email %>
	</div>
	<div class="row">
		<%= f.label :password, t(:password) %>
		<%= f.password_field :password %>
	</div>
	<div class="row">
		<%= f.label :password_confirmation, t(:password_confirmation) %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div>
  		<%= f.submit t(:signup) %>
	</div>
<% end -%>

app/views/accounts/show.html.erb
<h2><%=h @account.login %></h2>
<p>OpenID: <%= identifier(@account) %></p>

<%= render :partial => 'hcard', :locals => {:persona => @account.public_persona } if @account.public_persona	 %>